#
# Makefile for in-process debug/backtrace library
#
# Copyright 2026 Phoenix Systems
#
# This file is part of Phoenix-RTOS.
#
# %LICENSE%
#

NAME := libdbg
LOCAL_HEADERS := dbg.h
LOCAL_SRCS := dbg.c

include $(static-lib.mk)
